language: scala
jdk:
  - oraclejdk8
scala:
  - 2.12.0
before_script:
  - psql -c 'create database test;' -U postgres
  - mysql -e 'create database sorm_test;'
install: 
  mvn install -DskipTests=true -Dgpg.skip=true
