language: scala
jdk:
  - oraclejdk7
  - oraclejdk8
scala:
  - 2.10.4
  - 2.11.8
  - 2.12.1
matrix:
  exclude:
    - scala: 2.12.1
      jdk: oraclejdk7  
before_install:
  - psql -c 'create database test;' -U postgres
  - mysql -e 'create database sorm_test;'
install: 
  mvn test -Dgpg.skip=true
